### ISSUE TITLE
More a Question

### ISSUE THREAD

**Issue by Odianosen25** [martin-ger/MQTT_VPN#1]
Hello @martin-ger , 

First of all this is great work and thanks for this.

First when you say VPN, does it mean that one will be able to have access to the network the ESP32 for example is connected to? I want to be able to not only access the ESP32, but also other devices it has on the network. So The ESP32 acts as my VPN gateway as per say.

Do you think there is a possibility this can be done in Python? As I am looking at something like this, but in a Python3 environment.

Regards

**Comment by martin-ger** [comment]
I am sure, it can be done (but not by me ;-) ). The tun/tap interface is standard Linux and the crypto is also available for Python:
https://pynacl.readthedocs.io/en/stable/

**Comment by Odianosen25** [comment]
Ok thanks and will look into it

Kind regards
