### ISSUE TITLE
MQTT_vpn on the cloud

### ISSUE THREAD

**Issue by garudaonekh** [martin-ger/MQTT_VPN#10]
hi, instead of running MQTTvpn  on Linux machine, can I run it on cloud instead and access that cloud from another machine thru the cloud public ip? My scenario is to access from mobile phone

**Comment by martin-ger** [comment]
You can use any MQTT broker with this SW, given that you have the proper credential to use it. The server is agnostic to the type of traffic.

**Comment by garudaonekh** [comment]
i mean I want to run mqtt_vpn on a Linux cloud and access it from phone via the public ip of that Linux.

Here's the flow that I want:
Phone <---http--> Linux cloud(mqtt_vpn, mqtt broker)<---MqTT-->ESP32

**Comment by garudaonekh** [comment]
Phone1<---http-->Linux cloud<---MqTT-->ESP32
