### ISSUE TITLE
WebSocket(WS) support

### ISSUE THREAD

**Issue by garudaonekh** [martin-ger/MQTT_VPN#11]
Hello, I see that this project supports Websocket(WS) but the problem is it is close(the connection is dropped) after 1 or 2 seconds. I have no idea why. Any suggestion or configuration to solve this?

**Comment by garudaonekh** [comment]
Hello, I see that this project supports Websocket(WS) but the problem is it is close after 1 or 2 seconds. I have no idea why. Any suggestion or configuration to solve this?

**Comment by martin-ger** [comment]
Sorry, no experiences with WebSockets so far.

**Comment by garudaonekh** [comment]
It comes to my surprise that by switching to ESPAsyncWebserver, it works. 
But i am still struggling with some random crash when this library post received message to TCP stack.
