### ISSUE TITLE
Suggestion for having many clients(devices)

### ISSUE THREAD

**Issue by garudaonekh** [martin-ger/MQTT_VPN#19]
Hi,
I need suggestion for having multiple devices. Currently, I tested with two devices(10.0.1.2 and 10.1.3). The daemon[mqtt_vpn.c](https://github.com/martin-ger/MQTT_VPN/blob/master/mqtt_vpn.c) listen for response data from 10.0.1.1. What if I have 100 devices or 200 devices? Is it a good idea to implement subtopic for each devices, for example: 10.0.1.2 and 10.0.1.2/response?

Please give me suggestion for this as I am building Esp32 sprinkler system depending on this library.

**Comment by Pablo2048** [comment]
The client subscribe to only two topics IMHO - his own address and the broadcast one (https://github.com/martin-ger/MQTT_VPN/blob/6c2e21761bafff81b4302e523887d71a41bbfb51/mqtt_vpn_arduino/src/mqttif.cpp#L110 and the next one). You don't need any 'subtopic'...

**Comment by garudaonekh** [comment]
> The client subscribe to only two topics IMHO - his own address and the broadcast one (
> 
> https://github.com/martin-ger/MQTT_VPN/blob/6c2e21761bafff81b4302e523887d71a41bbfb51/mqtt_vpn_arduino/src/mqttif.cpp#L110
> 
> and the next one). You don't need any 'subtopic'...

Hi, i am referring to the daemon([mqtt_vpn.c](https://github.com/martin-ger/MQTT_VPN/blob/master/mqtt_vpn.c)). So far, I am fine with it, I have 2 ESP32 devices(10.0.1.2 and 10.0.1.3)

Let me clarify my question. For example, if I have 100 ESP32 devices and one user for each devices, how will the daemon handle it?

**Comment by Pablo2048** [comment]
The 'daemon' is just the same station as any ESP so it will subscribe to two topics: his own ip address and the broadcast one. If any station will communicate with the PC station it will publish to the PC station topic (his ip address) and awaits the reply (or replies) in its own topic (ip address).
See https://github.com/martin-ger/MQTT_VPN/blob/6c2e21761bafff81b4302e523887d71a41bbfb51/mqtt_vpn.c#L336 and the next line...

**Comment by garudaonekh** [comment]
> The 'daemon' is just the same station as any ESP so it will subscribe to two topics: his own ip address and the broadcast one. If any station will communicate with the PC station it will publish to the PC station topic (his ip address) and awaits the reply (or replies) in its own topic (ip address). See
> 
> https://github.com/martin-ger/MQTT_VPN/blob/6c2e21761bafff81b4302e523887d71a41bbfb51/mqtt_vpn.c#L336
> 
> and the next line...

I mean a single daemon with 100 ESP32 devices connected to it.

**Comment by Pablo2048** [comment]
Then it's not about daemon, but used MQTT broker instead. Just to make it short: every MQTT VPN client (any ESP or PC) will made 2 subscriptions. Traffic is determined by clients and your application (how many times, how fast, how often they will communicate). The VPN does just simple thing - client 'packs' every ip datagram do data part of topic and the topic itself came from destination ip address - its just unicast (single) ip address, or broadcast topic address.
