### ISSUE TITLE
Can't compile mqtt_vpn.c

### ISSUE THREAD

**Issue by aliumairs** [martin-ger/MQTT_VPN#5]
hello,

i was installing paho mqtt c client library and libnacl-dev on ubuntu 18.04.2 LTS, when me run a gcc compiler on terminal, it says error, 

bengkelrobot:~/Desktop/MQTT_VPN-master/paho.mqtt.c$ gcc mqtt_vpn.c
/tmp/ccYrhtKs.o: In function `msgarrvd':
mqtt_vpn.c:(.text+0x71e): undefined reference to `crypto_secretbox_xsalsa20poly1305_ref_open'
mqtt_vpn.c:(.text+0x7cb): undefined reference to `MQTTClient_freeMessage'
mqtt_vpn.c:(.text+0x7d7): undefined reference to `MQTTClient_free'
/tmp/ccYrhtKs.o: In function `main':
mqtt_vpn.c:(.text+0xc19): undefined reference to `crypto_hash_sha512_ref'
mqtt_vpn.c:(.text+0x1205): undefined reference to `MQTTClient_create'
mqtt_vpn.c:(.text+0x1242): undefined reference to `MQTTClient_setCallbacks'
mqtt_vpn.c:(.text+0x127d): undefined reference to `MQTTClient_connect'
mqtt_vpn.c:(.text+0x1360): undefined reference to `MQTTClient_subscribe'
mqtt_vpn.c:(.text+0x13cc): undefined reference to `MQTTClient_subscribe'
mqtt_vpn.c:(.text+0x16ee): undefined reference to `crypto_secretbox_xsalsa20poly1305_ref'
mqtt_vpn.c:(.text+0x174d): undefined reference to `MQTTClient_publishMessage'
collect2: error: ld returned 1 exit status

how to solve it?

note: sorry my english isn't good :)

**Comment by bwjohns4** [comment]
For anyone else having trouble building, see: https://github.com/martin-ger/MQTT_VPN/issues/13
